---
version: "2.1"

networks:
  TP1:
    external: false

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/aptalca/appdata/heimdall:/config
    restart: unless-stopped
    networks:
      - TP1

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=dockerswagduckdegab.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=9efb6250-0b01-4fd9-9398-e2fad91e9f8e
    volumes:
      - /home/aptalca/appdata/swag:/config
    ports:
      - '443:443'
      - '80:80'
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - TP1

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PMA_ARBITRARY=1 #optional
      - PMA_ABSOLUTE_URI=https://dockerswagduckdegab.duckdns.org/phpmyadmin #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - '8081:8081'
    restart: unless-stopped
    networks:
      - TP1

  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    ports:
      - '389:389'
      - '636:636'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - LDAP_ORGANISATION="TP Gabriel Fourtoy"
      - LDAP_DOMAIN="openldap.dockerswagduckdegab.duckdns.org"
    networks:
      - TP1

  ldap-gui:
    container_name: ldap-gui
    image: wheelybird/ldap-user-manager:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - LDAP_URI=https://openldap.dockerswagduckdegab.duckdns.org
      - LDAP_BASE_DN=dc=dockerswagduckdegab,dc=duckdns,dc=org
      - LDAP_ADMIN_BIND_DN=dc=admin,dc=dockerswagduckdegab,dc=duckdns,dc=org
      - LDAP_ADMIN_PW=admin
      - LDAP_ADMINS_GROUP=admins
    networks:
      - TP1

  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mariadbpassword
      - TZ=Europe/London
      - MYSQL_DATABASE=WP_database
      - MYSQL_USER=WP_dbuser
      - MYSQL_PASSWORD=WP_dbpassword
    volumes:
      - /home/aptalca/appdata/mariadb:/config
    restart: unless-stopped
    networks:
      - TP1

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - '8082:8082'
    links:
      - nextcloud_db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=cloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - TP1

  nextcloud_db:
    container_name: nextcloud_db
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=next
      - MYSQL_PASSWORD=cloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  plik:
    image: rootgg/plik:latest
    container_name: plik
    volumes:
      - ./plik/plikd.cfg:/home/plik/server/plikd.cfg
      - ./plik/data:/data
    ports:
      - '8083:8083'
    restart: "unless-stopped"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - TP1

  db_wordpress:
    container_name: db_wordpress
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    expose:
      - 3306
      - 33060

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 8084:8084
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db_wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - TP1
    links:
      - db_wordpress

  gitea:
    image: gitea/gitea:1.19.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    networks:
      - TP1
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8085:8085"

  spacedeck:
    image: spacedeck/spacedeck-open:latest
    container_name: spacedeck
    ports:
      - "8086:8086"
    volumes:
      - ./storage:/app/storage
      - ./database:/app/database
    networks:
        - TP1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8087:8087"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - TP1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London

  mattermost:
    image: mattermost/mattermost-preview:latest
    container_name: mattermost
    ports:
      - "8088:8088"
    networks:
      - TP1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London

volumes:
  db_data:
  wp_data:
  openldap_data:
    driver: local
  nextcloud:
  db:
  data:
